namespace Kucoin.Types

module OrderApiNs = 

    type OrderType =
        | Limit
        | Market

    type Side =
        | Buy
        | Sell


    //todo: auto generated by copilot, check accuracy
    type PlacedOrder = {
        OrderId: string
    }

    type PlaceOrderApiResponse = {
        Code: string
        Data: PlacedOrder
    }



    type OrderDetailsData = {
        OrderId: string
        Symbol: string
        Side: string
        Price: decimal
        Size: decimal
        CreateAt: int64
        UpdateAt: int64
        Status: string
        Leverage: decimal
        FilledSize: decimal
        FilledValue: decimal
    }


    type OrderDetailsApiResponse = {
        Code: string
        Data: OrderDetailsData
    }


    type OrdersData = {
        CurrentPage: int
        PageSize: int
        TotalNum: int
        TotalPage: int
        Items: List<OrderDetailsData>
    }

    type OrdersApiResponse = {
        Code: string
        Data: OrdersData
    }


    type PlaceOrderRequest = {
        clientoid: string
        symbol: string
        leverage: int
        side: Side
        ``type``: string
        size: decimal
        price: decimal option
    }